name: Reusable workflow test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ${{ inputs.runner }}
    steps:
      - run: echo ${{ inputs.runner }}
