name: Static Analysis
on:
  workflow_dispatch:
    
jobs:
  analyze-terraform:
    name: Terraform static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Static analysis - TFSEC
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif          

#       - name: Upload TFSEC SARIF file
#         uses: github/codeql-action/upload-sarif@v1
#         with:
#           sarif_file: tfsec.sarif

      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'azure'
          only_warn: true
          sarif_upload: true

      - name: Upload Terrascan SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: terrascan.sarif


      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.29.0

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
